Market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from article.sitemaps import PostSitemap
from article.views import post_list
from django.conf import settings
from django.conf.urls.static import static
from information.views import dashboard
from django.conf.urls.i18n import i18n_patterns

sitemaps = {'posts': PostSitemap, }

urlpatterns = i18n_patterns(
    path('', post_list),
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('information/', include('information.urls', namespace='information')),
    path('actions/', include('actions.urls', namespace='actions')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('accounts/profile/', dashboard),
    path('accounts/', include('allauth.urls')),
    path('rosetta/', include('rosetta.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

actions/urls.py
from django.urls import path
from . import views

app_name = 'actions'
urlpatterns = [
    path('create/', views.message_create, name='message_create'),
    path('conversation/<int:id>', views.conversation, name='conversation'),
    path('delete/<int:id>/', views.message_delete, name='message_delete'),
]

article/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'article'
urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('detail/<int:id>/', views.post_detail, name='post_detail'),
    path('share/<int:id>/', views.post_share, name='post_share'),
    # path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
    path('create/', views.post_create, name='post_create'),
    path('update/<int:id>/', views.post_update, name='post_update'),
    path('delete/<int:id>/', views.post_delete, name='post_delete'),
    path('like/', views.post_like, name='post_like'),
]

information/urls.py
from django.urls import path
from . import views

app_name = 'information'
urlpatterns = [
    path('', views.user_list, name='user_list'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('update/', views.profile_update, name='profile_update'),
    path('detail/<username>/', views.user_detail, name='user_detail'),
    path('follow/', views.user_follow, name="user_follow"),
]

information/models.py
from django.db import models
from django.conf import settings
from django.dispatch import receiver
from django.contrib.auth.models import User
from django.db.models.signals import post_save


# Create your models here.
class Contact(models.Model):
    user_from = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='rel_from_set', on_delete=models.CASCADE)
    user_to = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='rel_to_set', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{} follows {}'.format(self.user_from, self.user_to)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatar/%Y%m%d/', blank=True, default='default-avatar.jpg')
    date_of_birth = models.DateField(blank=True, null=True)
    description = models.TextField(max_length=500, blank=True, default='Hello!')
    following = models.ManyToManyField('self', through=Contact, related_name='followers', symmetrical=False)

    def __str__(self):
        return "Profile for user {}".format(self.user.username)


# 信号接收函数，每当新建 User 实例时自动调用
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


# 信号接收函数，每当更新 User 实例时自动调用
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

information/forms.py
from django import forms
from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('avatar', 'description')
        widgets = {
            'description': forms.Textarea(attrs={'class': 'w3-input w3-border'}),
        }

information/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import ProfileForm
from common.decorators import ajax_required
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from .models import Contact
from actions.utils import create_action
from actions.models import Action, Message


# Create your views here.
@login_required
def user_list(request):
    users = User.objects.all()
    tag = request.GET.get('tag')
    if tag and tag != 'None':
        followers = Contact.objects.filter(user_to=request.user).values_list('user_from', flat=True)[:10]
        followers = User.objects.filter(id__in=followers)
        following = Contact.objects.filter(user_from=request.user).values_list('user_to', flat=True)[:10]
        following = User.objects.filter(id__in=following)

        def intersection(lst1, lst2):
            lst3 = [value for value in lst1 if value in lst2]
            return lst3

        if tag == 'Followers':
            users = followers
        elif tag == 'Following':
            users = following
        elif tag == 'Friends':
            users = intersection(followers, following)
    return render(request, 'information/list.html', {'users': users})


@login_required
def user_detail(request, username):
    user = get_object_or_404(User, username=username)
    followers = Contact.objects.filter(user_to=user).values_list('user_from', flat=True)[:10]
    followers = User.objects.filter(id__in=followers)
    following = Contact.objects.filter(user_from=user).values_list('user_to', flat=True)[:10]
    following = User.objects.filter(id__in=following)
    actions = Action.objects.filter(user=user)[:100]
    return render(request,
                  'information/detail.html',
                  {'user': user,
                   'followers': followers,
                   'following': following,
                   'actions': actions})


@login_required
def dashboard(request):
    following = Contact.objects.filter(user_from=request.user).values_list('user_to', flat=True)[:10]
    following = User.objects.filter(id__in=following)
    actions = Action.objects.select_related('user', 'user__profile').prefetch_related('target').filter(
        user__in=following)[
              :100]
    msgs = Message.objects.filter(user_to=request.user)[:100]
    followers = Contact.objects.filter(user_to=request.user).values_list('user_from', flat=True)[:10]
    followers = User.objects.filter(id__in=followers)
    following = Contact.objects.filter(user_from=request.user).values_list('user_to', flat=True)[:10]
    following = User.objects.filter(id__in=following)

    return render(request,
                  'information/dashboard.html',
                  {'actions': actions,
                   'messages': msgs,
                   'followers': followers,
                   'following': following})


@login_required
def profile_update(request):
    if request.method == 'POST':
        form = ProfileForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        form = ProfileForm(instance=request.user.profile)
    return render(request, 'information/update.html', {'form': form})


@ajax_required
@require_POST
@login_required
def user_follow(request):
    user_id = request.POST.get('id')
    action = request.POST.get('action')
    if user_id and action:
        try:
            user = User.objects.get(id=user_id)
            if action == "follow":
                Contact.objects.get_or_create(user_from=request.user, user_to=user)
                create_action(request.user, 'is following', user)
            else:
                Contact.objects.filter(user_from=request.user, user_to=user).delete()
            return JsonResponse({'status': 'ok'})
        except User.DoesNotExist:
            return JsonResponse({'status': 'ko'})

    return JsonResponse({'status': 'ko'})

templates/information/dashboard.html
{% extends "base.html" %}
{% load i18n %}
{% load thumbnail %}
{% load article_tags %}
{% block title %}{% trans "Dashboard" %}{% endblock %}

{% block content %}
    <header>
        {% thumbnail user.profile.avatar "300x300" crop="100%" as im %}
            <a href="{{ user.get_absolute_url }}"><img src="{{ im.url }}" style="width:65px;"
                                                       class="w3-circle w3-right w3-margin w3-hide-large w3-hover-opacity"></a>
            </a>
        {% endthumbnail %}
        <span class="w3-button w3-hide-large w3-xxlarge w3-hover-text-grey" onclick="w3_open()"><i
                class="fa fa-bars"></i></span>
        <div class="w3-container">
            <h1><b>{% trans "DASHBOARD" %}</b></h1>
            <div class="w3-section w3-bottombar w3-padding-16">
                <a href="{% url "information:profile_update" %}" class="w3-button w3-white">
                    <i class="fas fa-id-card"></i>{% trans "Update profile" %}
                </a>
                <a href="{% url "account_change_password" %}" class="w3-button w3-white w3-hide-small">
                    <i class="fa fa-key"></i>{% trans "Change password" %}
                </a>
                <a href="{% url "actions:message_create" %}" class="w3-button w3-white w3-hide-small">
                    <i class="fa fa-envelope"></i>{% trans "Send message" %}
                </a>
                <a href="{% url "article:post_feed" %}" class="w3-button w3-white w3-hide-small">
                    <i class="fa fa-rss"></i>{% trans "RSS feed" %}
                </a>
                <a href="{% url 'article:post_list' %}?tag=收藏" class="w3-button w3-white w3-hide-small">
                    <i class="fa fa-star"></i>{% trans "Favourites" %}
                </a>
            </div>
        </div>
    </header>
    <div class="w3-row">
        <div class="w3-col l8 s12">
            <!-- Detail card -->
            <div class="w3-card-4 w3-margin">
                <div class="w3-container w3-padding">
                    <h4>{% trans "Posts" %}</h4>
                </div>
                <div class="w3-container w3-white w3-padding-16">
                    {% include "article/list_ajax.html" with posts=user.posts_created.all %}
                </div>
            </div>
            <hr>
            <div class="w3-card-4 w3-margin">
                <div class="w3-container w3-padding">
                    <h4>{% trans "What's happening" %}</h4>
                </div>
                <ul class="w3-ul w3-hoverable w3-white">
                    {% for action in actions %}
                        <li class="w3-padding-16">
                            {% include "actions/detail.html" %}
                        </li>
                    {% empty %}
                        <div class="w3-container w3-white">
                            <p>{% trans "There is nothing happened." %}</p>
                        </div>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="w3-col l4">
            <!-- About Card -->
            <div class="w3-card w3-margin w3-margin-top">
                {% thumbnail user.profile.avatar "300x300" crop="100%" as im %}
                    <a href="{{ user.get_absolute_url }}">
                        <img src="{{ im.url }}" style="width:100%">
                    </a>
                {% endthumbnail %}
                <div class="w3-container w3-white">
                    <h4><b>{{ user.username }}</b></h4>
                    <p>{{ user.profile.description|markdown }}</p>
                </div>
            </div>
            <hr>
            <!-- Messages -->
            <div class="w3-card w3-margin">
                <div class="w3-container w3-padding">
                    <h4>{% trans "Messages" %}</h4>
                </div>
                <ul class="w3-ul w3-hoverable w3-white">
                    {% for message in messages %}
                        <li class="w3-padding-16">
                            {% include "actions/message.html" %}
                        </li>
                    {% empty %}
                        <div class="w3-container w3-white">
                            <p>{% trans "There are no messages yet." %}</p>
                        </div>
                    {% endfor %}
                </ul>
            </div>
            <!-- Followers -->
            <div class="w3-card w3-margin">
                <div class="w3-container w3-padding">
                    <h4>{% trans "Followers" %}</h4>
                </div>
                {% include 'information/list_ul.html' with users=followers %}
            </div>
            <!-- Following -->
            <div class="w3-card w3-margin">
                <div class="w3-container w3-padding">
                    <h4>{% trans "Following" %}</h4>
                </div>
                {% include 'information/list_ul.html' with users=following %}
            </div>
        </div>
    </div>

{% endblock %}

templates/information/detail.html
{% extends "base.html" %}
{% load article_tags %}
{% load i18n %}
{% load information_tags %}
{% load thumbnail %}
{% block title %}{{ user.username }}{% endblock %}
{% block content %}
    {% thumbnail user.profile.avatar "300x300" crop="100%" as im %}
        <a href="{{ user.get_absolute_url }}"><img src="{{ im.url }}" style="width:65px;"
                                                   class="w3-circle w3-right w3-margin w3-hide-large w3-hover-opacity"></a>
        </a>
    {% endthumbnail %}
    <span class="w3-button w3-hide-large w3-xxlarge w3-hover-text-grey" onclick="w3_open()"><i
            class="fa fa-bars"></i></span>
    <div class="w3-row">
        <!-- Big cards -->
        <div class="w3-col l8 s12">
            <!-- Detail card -->
            <div class="w3-card-4 w3-margin">
                <div class="w3-container w3-padding">
                    <h4>{% trans "Posts" %}</h4>
                </div>
                <div class="w3-container w3-white w3-padding-16">
                    {% include "article/list_ajax.html" with posts=user.posts_created.all %}
                </div>
            </div>
            <hr>
            <div class="w3-card-4 w3-margin">
                <div class="w3-container w3-padding">
                    <h4>{% trans "What's happening" %}</h4>
                </div>
                <ul class="w3-ul w3-hoverable w3-white">
                    {% for action in actions %}
                        <li class="w3-padding-16">
                            {% include "actions/detail.html" %}
                        </li>
                    {% empty %}
                        <div class="w3-container w3-white">
                            <p>{% trans "There is nothing happened." %}</p>
                        </div>
                    {% endfor %}
                </ul>
            </div>
            <!-- END BIG CARDS -->
        </div>

        <!-- Introduction menu -->
        <div class="w3-col l4">
            <!-- About Card -->
            <div class="w3-card w3-margin w3-margin-top">
                {% thumbnail user.profile.avatar "300x300" crop="100%" as im %}
                    <a href="{{ user.get_absolute_url }}">
                        <img src="{{ im.url }}" style="width:100%">
                    </a>
                {% endthumbnail %}
                <div class="w3-container w3-white">
                    <h4><b>{{ user.username }}</b></h4>
                    {% if user != request.user %}
                        <button class="w3-button {% follow_color request.user user %}" id="follow-button">
                            <i class="fas fa-heart"></i>
                            <span class="count">
                                <span class="total">{% followers_count user %}</span>
                                {% trans "followers" %}
                            </span>
                        </button>

                        <a class="w3-button w3-light-gray" href="{% url 'actions:conversation' user.id %}">
                            <i class="fas fa-envelope"></i>
                            {% trans "Contact" %}
                        </a>
                    {% endif %}
                    <a href="#" data-id="{{ user.id }}"
                       data-action="{% follow_action request.user user %}" class="follow button" id="follow-link"
                       style="display: none">
                        {% show_follow request.user user %}
                    </a>
                    <p>{{ user.profile.description|markdown }}</p>
                </div>
            </div>
            <hr>
            <!-- Followers -->
            <div class="w3-card w3-margin">
                <div class="w3-container w3-padding">
                    <h4>{% trans "Followers" %}</h4>
                </div>
                {% include 'information/list_ul.html' with users=followers %}
            </div>
            <!-- Following -->
            <div class="w3-card w3-margin">
                <div class="w3-container w3-padding">
                    <h4>{% trans "Following" %}</h4>
                </div>
                {% include 'information/list_ul.html' with users=following %}
            </div>
            <!-- END Introduction Menu -->
        </div>
    </div>
{% endblock %}
{% block domready %}
    <script>
        $(document).ready(function () {
            $('a.follow').click(function (e) {
                e.preventDefault();
                $.post('{% url "information:user_follow" %}',
                    {
                        id: $(this).data('id'),
                        action: $(this).data('action')
                    },
                    function (data) {
                        if (data['status'] == 'ok') {
                            var previous_action = $('a.follow').data('action');

                            // toggle data-action
                            $('a.follow').data('action',
                                previous_action == 'follow' ? 'unfollow' : 'follow');
                            // toggle link text
                            $('a.follow').text(
                                previous_action == 'follow' ? 'Unfollow' : 'Follow');

                            // update total followers
                            var previous_followers = parseInt(
                                $('span.count .total').text());
                            $('span.count .total').text(previous_action == 'follow' ? previous_followers + 1 : previous_followers - 1);

                            if (previous_action == 'follow')
                                $('#follow-button').removeClass('w3-light-gray').addClass('w3-black');
                            else $('#follow-button').removeClass('w3-black').addClass('w3-light-gray');
                        }
                    }
                );
            });
            $('#follow-button').click(function (e) {
                $('#follow-link').click();
                return false;
            });
        });
    </script>
{% endblock %}

templates/information/list.html
{% extends "base.html" %}
{% load thumbnail %}
{% load i18n %}
{% block title %}{% trans "People" %}{% endblock %}
{% block content %}
    <header>
        {% thumbnail user.profile.avatar "300x300" crop="100%" as im %}
            <a href="{{ user.get_absolute_url }}"><img src="{{ im.url }}" style="width:65px;"
                                                       class="w3-circle w3-right w3-margin w3-hide-large w3-hover-opacity"></a>
            </a>
        {% endthumbnail %}
        <span class="w3-button w3-hide-large w3-xxlarge w3-hover-text-grey" onclick="w3_open()"><i
                class="fa fa-bars"></i></span>
        <div class="w3-container">
            <h1><b>
                {% if tag %}
                    {{ tag }}
                {% else %}
                    {% trans "Users" %}
                {% endif %}
            </b></h1>
            <div class="w3-section w3-bottombar w3-padding-16">
                <a class="w3-button w3-white" href="{% url 'information:user_list' %}">{% trans "ALL" %}</a>
                <a class="w3-button w3-white" href="{% url 'information:user_list' %}?tag=Followers">{% trans "Followers" %}</a>
                <a class="w3-button w3-white" href="{% url 'information:user_list' %}?tag=Following">{% trans "Following" %}</a>
                <a class="w3-button w3-white" href="{% url 'information:user_list' %}?tag=Friends">{% trans "Friends" %}</a>
            </div>
        </div>
    </header>
    {% include "information/list_ajax.html" %}
{% endblock %}

templates/information/list_ajax.html
{% load thumbnail %}
{% load i18n %}
<div class="w3-row-padding">
    {% for user in users %}
        <div class="w3-col l3 m6 w3-margin-bottom">
            <div class="w3-display-container">
                <div class="w3-display-topleft w3-black w3-padding">
                    {{ user.username }}
                </div>
                {% thumbnail user.profile.avatar "300x300" crop="100%" as im %}
                    <a href="{{ user.get_absolute_url }}">
                        <img src="{{ im.url }}" style="width:100%">
                    </a>
                {% endthumbnail %}
            </div>
        </div>
    {% endfor %}
</div>

templates/information/list_ul.html
{% load i18n %}
{% load thumbnail %}
<ul class="w3-ul w3-hoverable w3-white">
    {% for user in users %}
        <li class="w3-padding-16">
            {% thumbnail user.profile.avatar "80x80" crop="100%" as im %}
                <a href="{{ user.get_absolute_url }}">
                    <img src="{{ im.url }}" alt="Image" class="w3-left w3-margin-right"
                         style="width:50px">
                </a>
            {% endthumbnail %}
            <span class="w3-large">{{ user.username }}</span><br>
            <span>{{ user.profile.description|truncatewords_html:5 }}</span>
        </li>
    {% empty %}
        <div class="w3-container w3-white">
            <p>{% trans "No users yet." %}</p>
        </div>
    {% endfor %}
</ul>

templates/information/update.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load thumbnail %}
{% block title %}
    {% trans "Edit your account" %}
{% endblock %}

{% block content %}
    {% thumbnail user.profile.avatar "300x300" crop="100%" as im %}
        <a href="{{ user.get_absolute_url }}"><img src="{{ im.url }}" style="width:65px;"
                                                   class="w3-circle w3-right w3-margin w3-hide-large w3-hover-opacity"></a>
        </a>
    {% endthumbnail %}
    <span class="w3-button w3-hide-large w3-xxlarge w3-hover-text-grey" onclick="w3_open()"><i
            class="fa fa-bars"></i></span>
    <div class="w3-container w3-padding-large" style="margin-bottom:32px">
        <h1>{% trans "Edit your account" %}</h1>
        <form action="." method="post" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            <p><label for="id_avatar">{% trans "Avatar:" %}</label> {{ form.avatar }}</p>
            <div id="editormd">
                <textarea name="description" id="id_description"
                          style="display:none">{{ form.description.value }}</textarea>
            </div>
            <p><input type="submit" value="{% trans 'Save changes' %}" class="w3-button w3-white"></p>
        </form>
    </div>
{% endblock %}
{% block domready %}
    <script>
        $(function () {
            var editor = editormd("editormd", {
                height: 500,
                syncScrolling: "single",
                path: "{% static 'editormd/lib/' %}" // Autoload modules mode, codemirror, marked... dependents libs path
            });
        });
    </script>
{% endblock %}