Market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from article.sitemaps import PostSitemap
from article.views import post_list
from django.conf import settings
from django.conf.urls.static import static
from information.views import dashboard
from django.conf.urls.i18n import i18n_patterns

sitemaps = {'posts': PostSitemap, }

urlpatterns = i18n_patterns(
    path('', post_list),
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('information/', include('information.urls', namespace='information')),
    path('actions/', include('actions.urls', namespace='actions')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('accounts/profile/', dashboard),
    path('accounts/', include('allauth.urls')),
    path('rosetta/', include('rosetta.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

actions/urls.py
from django.urls import path
from . import views

app_name = 'actions'
urlpatterns = [
    path('create/', views.message_create, name='message_create'),
    path('conversation/<int:id>', views.conversation, name='conversation'),
    path('delete/<int:id>/', views.message_delete, name='message_delete'),
]

actions/models.py
from django.db import models
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey


# Create your models here.
class Action(models.Model):
    user = models.ForeignKey('auth.user', related_name='actions', db_index=True, on_delete=models.CASCADE)
    verb = models.CharField(max_length=255)
    target_ct = models.ForeignKey(ContentType, blank=True, null=True, related_name='target_obj',
                                  on_delete=models.CASCADE)
    target_id = models.PositiveIntegerField(null=True, blank=True, db_index=True)
    target = GenericForeignKey('target_ct', 'target_id')
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created',)


class Message(models.Model):
    user_from = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='msg_from', on_delete=models.CASCADE)
    user_to = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='msg_to', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    body = models.TextField()

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{} sends message to {}'.format(self.user_from, self.user_to)

actions/forms.py
from django import forms
from .models import Message

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('user_to', 'body')
        widgets = {
            'user_to': forms.Select(attrs={'class': 'w3-select w3-border'}),
            'body': forms.Textarea(attrs={'class': 'w3-input w3-border'}),
        }

actions/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import MessageForm
from .models import Message
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from django.db.models import Q


# Create your views here.
@login_required
def message_create(request):
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            new_item = form.save(commit=False)
            new_item.user_from = request.user
            new_item.save()
            messages.success(request, 'Message sent successfully')
            return redirect('actions:conversation', id=new_item.user_to.id)
    else:
        id = request.GET.get('id')
        user = None
        if id and id != 'None':
            user = get_object_or_404(User, id=id)
        if user:
            form = MessageForm(initial={'user_to': user})
        else:
            form = MessageForm()
        return render(request, 'actions/create.html', {'form': form})


@login_required
def message_delete(request, id):
    message = get_object_or_404(Message, id=id)
    if request.user not in [message.user_from, message.user_to]:
        return redirect('information:dashboard')
    message.delete()
    if request.user == message.user_from:
        return redirect('actions:conversation', id=message.user_to.id)
    else:
        return redirect('actions:conversation', id=message.user_from.id)


@login_required
def conversation(request, id):
    user = get_object_or_404(User, id=id)
    msgs = Message.objects.filter(Q(user_from=request.user, user_to=user) | Q(user_from=user, user_to=request.user))
    return render(request, 'actions/conversation.html', {'user': user, 'messages': msgs})

templates/actions/conversation.html
{% extends "base.html" %}
{% load i18n %}
{% load thumbnail %}
{% load article_tags %}
{% block title %}Conversation with {% endblock %}

{% block content %}
    <header>
        {% thumbnail user.profile.avatar "300x300" crop="100%" as im %}
            <a href="{{ user.get_absolute_url }}"><img src="{{ im.url }}" style="width:65px;"
                                                       class="w3-circle w3-right w3-margin w3-hide-large w3-hover-opacity"></a>
            </a>
        {% endthumbnail %}
        <span class="w3-button w3-hide-large w3-xxlarge w3-hover-text-grey" onclick="w3_open()"><i
                class="fa fa-bars"></i></span>
        <div class="w3-container">
            <h1><b>{% trans "Conversation" %}</b></h1>
            <div class="w3-section w3-bottombar w3-padding-16">
                <a href="{% url 'actions:message_create' %}?id={{ user.id }}" class="w3-button w3-white w3-hide-small">
                    <i class="fa fa-envelope"></i>{% trans "Send message" %}
                </a>
            </div>
        </div>
    </header>
    <div class="w3-row">
        <div class="w3-col l8 s12">
            <div class="w3-card-4 w3-margin">
                <div class="w3-container w3-padding">
                    <h4>{% trans "Messages" %}</h4>
                </div>
                <ul class="w3-ul w3-hoverable w3-white">
                    {% for message in messages %}
                        <li class="w3-padding-16">
                            {% include "actions/message_full.html" %}
                        </li>
                    {% empty %}
                        <div class="w3-container w3-white">
                            <p>{% trans "There are no messages yet." %}</p>
                        </div>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <hr>
        <div class="w3-col l4">
            <!-- About Card -->
            <div class="w3-card w3-margin w3-margin-top">
                {% thumbnail user.profile.avatar "300x300" crop="100%" as im %}
                    <a href="{{ user.get_absolute_url }}">
                        <img src="{{ im.url }}" style="width:100%">
                    </a>
                {% endthumbnail %}
                <div class="w3-container w3-white">
                    <h4><b>{{ user.username }}</b></h4>
                    <p>{{ user.profile.description|markdown }}</p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/actions/create.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load thumbnail %}
{% block title %}{% trans "Send a message" %}{% endblock %}
{% block content %}
    {% thumbnail user.profile.avatar "300x300" crop="100%" as im %}
            <a href="{{ user.get_absolute_url }}"><img src="{{ im.url }}" style="width:65px;"
                                                       class="w3-circle w3-right w3-margin w3-hide-large w3-hover-opacity"></a>
            </a>
        {% endthumbnail %}
        <span class="w3-button w3-hide-large w3-xxlarge w3-hover-text-grey" onclick="w3_open()"><i
                class="fa fa-bars"></i></span>
    <div class="w3-container w3-padding-large" style="margin-bottom:32px">
        <h1>{% trans "Send a message" %}</h1>
        <form action="" method="post">
            {% csrf_token %}
            <p>
                <label for="id_user_to">{% trans "User to:" %}</label>
                {{ form.user_to }}
            </p>
            <div id="editormd">
                <textarea name="body" id="id_body" style="display:none"></textarea>
            </div>
            <p><input type="submit" value="{% trans 'Send' %}"
                      class="w3-button w3-padding-large w3-white w3-border"></p>
        </form>
    </div>
{% endblock %}
{% block domready %}
    <script>
        $(function () {
            var editor = editormd("editormd", {
                height: 500,
                syncScrolling: "single",
                path: "{% static 'editormd/lib/' %}" // Autoload modules mode, codemirror, marked... dependents libs path
            });
        });
    </script>
{% endblock %}

templates/actions/detail.html
{% load thumbnail %}
{% load i18n %}
{% with user=action.user profile=action.user.profile %}
    {% if action.target %}
        {% with target=action.target %}
            {% if target.profile.avatar %}
                {% thumbnail target.profile.avatar "80x80" crop="100%" as im %}
                    <a href="{{ target.get_absolute_url }}">
                        <img src="{{ im.url }}" alt="Image" class="w3-left w3-margin-right"
                             style="width:50px">
                    </a>
                {% endthumbnail %}
            {% elif target.avatar %}
                {% thumbnail target.avatar "80x80" crop="100%" as im %}
                    <a href="{{ target.get_absolute_url }}">
                        <img src="{{ im.url }}" alt="Image" class="w3-left w3-margin-right"
                             style="width:50px">
                    </a>
                {% endthumbnail %}
            {% endif %}
        {% endwith %}
    {% endif %}
    <span class="w3-large">
        <a href="{{ user.get_absolute_url }}">{{ user.username }}</a>
        {% trans action.verb %}
        {% if action.target %}
            {% with target=action.target %}
                <a href="{{ target.get_absolute_url }}">{{ target }}</a>
            {% endwith %}
        {% endif %}
    </span><br>
    <span>{{ action.created|timesince }} {% trans "ago" %}</span>
{% endwith %}

templates/actions/message.html
{% load thumbnail %}

{% thumbnail message.user_from.profile.avatar "80x80" crop="100%" as im %}
    <a href="{{ message.user_from.get_absolute_url }}">
        <img src="{{ im.url }}" alt="Image" class="w3-left w3-margin-right"
             style="width:50px">
    </a>
{% endthumbnail %}
<span class="w3-large">{{ message.user_from.username|truncatewords:5 }}</span>
<span class="w3-large w3-opacity">, {{ message.created|timesince }} ago</span>
<br>
<span style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; display: block">{{ message.body }}</span>

templates/actions/message_full.html
{% load thumbnail %}
{% load article_tags %}
{% load i18n %}
{% thumbnail message.user_from.profile.avatar "80x80" crop="100%" as im %}
    <a href="{{ message.user_from.get_absolute_url }}">
        <img src="{{ im.url }}" alt="Image" class="w3-left w3-margin-right"
             style="width:50px">
    </a>
{% endthumbnail %}
<span class="w3-large">{{ message.user_from.username }}</span>
<span class="w3-large w3-opacity">, {{ message.created|timesince }} {% trans "ago" %} <a
        href="{% url 'actions:message_delete' message.id %}">{% trans "Delete" %}</a></span>
<br>
<span>{{ message.body|markdown }}</span>

templates/actions/words.html
{% load i18n %}
{% trans "likes" %}
{% trans "created post" %}
{% trans "commented post" %}
{% trans "is following" %}