Market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from article.sitemaps import PostSitemap
from article.views import post_list
from django.conf import settings
from django.conf.urls.static import static
from information.views import dashboard
from django.conf.urls.i18n import i18n_patterns

sitemaps = {'posts': PostSitemap, }

urlpatterns = i18n_patterns(
    path('', post_list),
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('information/', include('information.urls', namespace='information')),
    path('actions/', include('actions.urls', namespace='actions')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('accounts/profile/', dashboard),
    path('accounts/', include('allauth.urls')),
    path('rosetta/', include('rosetta.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'article'
urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('detail/<int:id>/', views.post_detail, name='post_detail'),
    path('share/<int:id>/', views.post_share, name='post_share'),
    # path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
    path('create/', views.post_create, name='post_create'),
    path('update/<int:id>/', views.post_update, name='post_update'),
    path('delete/<int:id>/', views.post_delete, name='post_delete'),
    path('like/', views.post_like, name='post_like'),
]

information/urls.py
from django.urls import path
from . import views

app_name = 'information'
urlpatterns = [
    path('', views.user_list, name='user_list'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('update/', views.profile_update, name='profile_update'),
    path('detail/<username>/', views.user_detail, name='user_detail'),
    path('follow/', views.user_follow, name="user_follow"),
]

templates/base.html
{% load article_tags %}
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'w3.css' %}">
    <link rel="stylesheet" href="{% static 'editormd/editormd.min.css' %}">
    <link href="https://cdn.bootcss.com/font-awesome/5.8.2/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.proxy.ustclug.org/css?family=Raleway">
    <style>
        body, h1, h2, h3, h4, h5, h6 {
            font-family: "Raleway", sans-serif
        }
    </style>
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
</head>
<body class="w3-light-grey w3-content" style="max-width:1600px">
{% include 'header.html' %}
<div class="w3-main" style="margin-left:300px">
    {% block content %}
    {% endblock %}
</div>
<script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/js-cookie/latest/js.cookie.min.js"></script>
<script src="{% static 'editormd/editormd.min.js' %}"></script>
<script>
    let csrftoken = Cookies.get('csrftoken');

    function csrfSafeMethon(method) {
        // 如下的HTTP请求不需要设置CRSF信息
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethon(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
</script>
{% block domready %}{% endblock %}
</body>
</html>

templates/header.html
<!-- 定义导航栏 -->
<!-- Sidebar/menu -->
{% load i18n %}
<nav class="w3-sidebar w3-collapse w3-white" style="z-index:3;width:300px;" id="mySidebar"><br>
    <div class="w3-container">
        <a href="#" onclick="w3_close()" class="w3-hide-large w3-right w3-jumbo w3-padding w3-hover-grey"
           title="close menu">
            <i class="fa fa-remove"></i>
        </a>
        {% load thumbnail %}
        {% thumbnail user.profile.avatar "300x300" crop="100%" as im %}
            <a href="{% url 'information:dashboard' %}">
                <img src="{{ im.url }}" style="width:45%;" class="w3-round"><br><br>
            </a>
        {% endthumbnail %}

        <h4><b>MARKET</b></h4>
        <p><a class="w3-text-grey" href="https://github.com/ndsf" style="text-decoration: none">By ndsf</a></p>
    </div>
    <div class="w3-bar-block">
        <a href="{% url 'article:post_list' %}" onclick="w3_close()"
           class="w3-bar-item w3-button w3-padding w3-text-teal"><i
                class="fas fa-th-large fa-fw w3-margin-right"></i>{% trans "POSTS" %}</a>
        <a href="{% url 'information:user_list' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-padding"><i
                class="fas fa-user fa-fw w3-margin-right"></i>{% trans "USERS" %}</a>
        <a href="{% url 'article:post_create' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-padding"><i
                class="fas fa-plus-square fa-fw w3-margin-right"></i>{% trans "CREATE" %}</a>

        {% if user.is_authenticated %}
            <!-- 如果用户已经登录，则显示用户名下拉框 -->
            <a href="{% url 'information:dashboard' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-padding"><i
                    class="fas fa-tachometer-alt fa-fw w3-margin-right"></i>{% trans "DASHBOARD" %}</a>
            <a href="{% url 'account_logout' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-padding"><i
                    class="fas fa-sign-out-alt fa-fw w3-margin-right"></i>{% trans "LOGOUT" %}</a>
            <!-- 如果用户未登录，则显示 “登录” -->
        {% else %}
            <a href="{% url 'account_login' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-padding"><i
                    class="fa fa-envelope fa-fw w3-margin-right"></i>{% trans "LOGIN" %}</a>
            <a href="{% url 'account_signup' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-padding"><i
                    class="fa fa-envelope fa-fw w3-margin-right"></i>{% trans "REGISTER" %}</a>
            <!-- if 语句在这里结束 -->
        {% endif %}
    </div>
    {% get_current_language as LANGUAGE_CODE %}
    {% get_available_languages as LANGUAGES %}
    {% get_language_info_list for LANGUAGES as languages %}
    <div class="w3-container">
        <p class="w3-text-grey">{% trans "Language" %}:</p>
        <ul class="w3-ul">
            {% for language in languages %}
                <li {% if language.code == LANGUAGE_CODE %} class="w3-light-gray"{% endif %}>
                    <a href="/{{ language.code }}/" style="text-decoration: none">
                        {{ language.name_local }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="w3-container">
        <p>
        <i class="fab fa-github w3-hover-opacity"></i>
        <i class="fab fa-google w3-hover-opacity"></i>
        <a class="w3-text-gray" href="{% url 'admin:index' %}" style="text-decoration: none"> {% trans "Admin" %},</a>
        <a class="w3-text-gray" href="{% url 'rosetta-old-home-redirect' %}" style="text-decoration: none"> {% trans "Help translation"%}</a>
        </p>
    </div>
</nav>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer"
     title="close side menu" id="myOverlay"></div>

<script>
    // Script to open and close sidebar
    function w3_open() {
        document.getElementById("mySidebar").style.display = "block";
        document.getElementById("myOverlay").style.display = "block";
    }

    function w3_close() {
        document.getElementById("mySidebar").style.display = "none";
        document.getElementById("myOverlay").style.display = "none";
    }
</script>