Market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from article.sitemaps import PostSitemap
from article.views import post_list
from django.conf import settings
from django.conf.urls.static import static
from information.views import dashboard
from django.conf.urls.i18n import i18n_patterns

sitemaps = {'posts': PostSitemap, }

urlpatterns = i18n_patterns(
    path('', post_list),
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('information/', include('information.urls', namespace='information')),
    path('actions/', include('actions.urls', namespace='actions')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('accounts/profile/', dashboard),
    path('accounts/', include('allauth.urls')),
    path('rosetta/', include('rosetta.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

actions/urls.py
from django.urls import path
from . import views

app_name = 'actions'
urlpatterns = [
    path('create/', views.message_create, name='message_create'),
    path('conversation/<int:id>', views.conversation, name='conversation'),
    path('delete/<int:id>/', views.message_delete, name='message_delete'),
]

article/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'article'
urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('detail/<int:id>/', views.post_detail, name='post_detail'),
    path('share/<int:id>/', views.post_share, name='post_share'),
    # path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
    path('create/', views.post_create, name='post_create'),
    path('update/<int:id>/', views.post_update, name='post_update'),
    path('delete/<int:id>/', views.post_delete, name='post_delete'),
    path('like/', views.post_like, name='post_like'),
]

article/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.models import User
from uuslug import slugify
from taggit.managers import TaggableManager


# Create your models here.

class Post(models.Model):
    # STATUS_CHOICES = (('draft', 'Draft'), ('published', 'Published'))

    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='posts_created', on_delete=models.CASCADE)

    avatar = models.ImageField(upload_to='images/%Y%m%d/', blank=True, default='default-post.png')
    body = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    # publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    updated = models.DateTimeField(auto_now=True)
    # status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='published')

    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='posts_liked', blank=True)
    total_likes = models.PositiveIntegerField(db_index=True, default=0)
    # objects = models.Manager()
    tags = TaggableManager(blank=True)

    class Meta:
        ordering = ('-updated',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article:post_detail', args=[self.id])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='comments_created', on_delete=models.CASCADE, null=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

article/forms.py
from django import forms
from .models import Comment, Post
from django.utils.translation import gettext_lazy as _


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, label=_('Name'))
    email = forms.EmailField(label=_('Email'))
    to = forms.EmailField(label=_('To'))
    comments = forms.CharField(required=False, widget=forms.Textarea, label=_('Comments'))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'class': 'w3-input w3-border'}),
        }


class SearchForm(forms.Form):
    query = forms.CharField()
    widgets = {
        'query': forms.TextInput(attrs={'class': 'w3-input w3-border'}),
    }


class PostForm(forms.ModelForm):
    price = forms.DecimalField(required=True, max_digits=6, min_value=0)
    class Meta:
        model = Post
        fields = ('title', 'avatar', 'price', 'body', 'tags')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'w3-input w3-border'}),
            'price': forms.TextInput(attrs={'class': 'w3-input w3-border'}),
            'body': forms.Textarea(attrs={'class': 'w3-input w3-border'}),
            'tags': forms.TextInput(attrs={'class': 'w3-input w3-border'}),
        }


class PostUpdateForm(forms.ModelForm):
    price = forms.DecimalField(required=True, max_digits=6, min_value=0)
    class Meta:
        model = Post
        fields = ('title', 'avatar', 'price', 'body')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'w3-input w3-border'}),
            'price': forms.TextInput(attrs={'class': 'w3-input w3-border'}),
            'body': forms.Textarea(attrs={'class': 'w3-input w3-border'}),
        }

article/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post
from .forms import EmailPostForm, CommentForm, SearchForm, PostForm, PostUpdateForm
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse, HttpResponse
from django.views.decorators.http import require_POST
from common.decorators import ajax_required
from actions.utils import create_action, delete_action
import redis
from django.conf import settings
from django.db.models import Q

# connect to redis
r = redis.StrictRedis(host=settings.REDIS_HOST,
                      port=settings.REDIS_PORT,
                      db=settings.REDIS_DB)


# Create your views here.

def post_list(request):
    posts = Post.objects.all()

    tag = request.GET.get('tag')
    if tag and tag != 'None':
        if tag == '收藏':
            posts = request.user.posts_liked.all()
        else:
            posts = posts.filter(tags__name__in=[tag])

    paginator = Paginator(posts, 9)
    page = request.GET.get('page')

    form = SearchForm()
    query = None
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.objects.filter(
                Q(title__icontains=query)
            )
        return render(request,
                      'article/search.html',
                      {'form': form,
                       'query': query,
                       'results': results})

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # 如果页数不是整数，就返回第一页
        posts = paginator.page(1)
    except EmptyPage:
        # 如果是不存在的页数，而且请求是AJAX请求，返回空字符串
        if request.is_ajax():
            return HttpResponse('')
        # 如果页数超范围，显示最后一页
        posts = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request, 'article/list_ajax.html', {'posts': posts, 'tag': tag, 'form': form})
    return render(request, 'article/list.html', {'posts': posts, 'tag': tag, 'form': form})


@login_required
def post_detail(request, id):
    post = get_object_or_404(Post, id=id)

    # increment total post views by 1
    total_views = r.incr('post:{}:views'.format(post.id))
    # increment post ranking by 1
    r.zincrby('post_ranking', post.id, 1)

    # 列出文章对应的所有活动的评论
    comments = post.comments.all()

    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            # 通过表单直接创建新数据对象，但是不要保存到数据库中
            new_comment = comment_form.save(commit=False)
            # 设置外键为当前文章
            new_comment.post = post
            new_comment.author = request.user
            create_action(request.user, 'commented post', post)
            # 将评论数据对象写入数据库
            new_comment.save()
    else:
        comment_form = CommentForm()

    # 显示相近Tag的文章列表
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_tags = Post.objects.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_tags.annotate(same_tags=Count('tags')).order_by('-same_tags', '-updated')[:4]
    return render(request, 'article/detail.html',
                  {'post': post, 'comments': comments, 'new_comment': new_comment, 'comment_form': comment_form,
                   'similar_posts': similar_posts, 'total_views': total_views})


def post_share(request, id):
    # 通过id 获取 post 对象
    post = get_object_or_404(Post, id=id)
    sent = False

    if request.method == 'POST':
        # 表单被提交
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # 验证表单数据
            cd = form.cleaned_data
            # 发送邮件......
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments:{}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'lee0709@vip.sina.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'article/share.html', {'post': post, 'form': form})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.objects.filter(
                Q(title__icontains=query)
            )
    return render(request,
                  'article/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})


@login_required
def post_create(request):
    if request.method == 'POST':
        # 表单被提交
        form = PostForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            new_item = form.save(commit=False)
            # 将当前用户附加到数据对象上
            new_item.author = request.user
            new_item.save()
            create_action(request.user, 'created post', new_item)
            form.save_m2m()
            messages.success(request, 'Post added successfully')
            # 重定向到新创建的数据对象的详情视图
            return redirect(new_item.get_absolute_url())
        else:
            return redirect('article:post_list')
    else:
        # 根据GET请求传入的参数建立表单对象
        form = PostForm(data=request.GET)
        return render(request, 'article/create.html', {'form': form})


@login_required
def post_update(request, id):
    post = get_object_or_404(Post, id=id)
    if request.user != post.author:
        return redirect(post.get_absolute_url())
    if request.method == 'POST':
        form = PostUpdateForm(instance=post, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Post updated successfully')
            return redirect(post.get_absolute_url())
        else:
            messages.error(request, 'Error updating your profile')
            return redirect(post.get_absolute_url())
    else:
        form = PostForm(instance=post)
        return render(request, 'article/update.html', {'form': form})


@login_required
def post_delete(request, id):
    post = get_object_or_404(Post, id=id)
    if request.user != post.author:
        return redirect(post.get_absolute_url())
    delete_action(post)
    post.delete()
    return redirect('article:post_list')


@ajax_required
@login_required
@require_POST
def post_like(request):
    post_id = request.POST.get('id')
    action = request.POST.get('action')
    if post_id and action:
        try:
            post = Post.objects.get(id=post_id)
            if action == 'like':
                post.users_like.add(request.user)
                create_action(request.user, 'likes', post)
            else:
                post.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except:
            pass
    return JsonResponse({'status': 'ko'})


def post_ranking(request):
    # get post ranking dictionary
    post_ranking = r.zrange('post_ranking', 0, -1, desc=True)[:10]
    post_ranking_ids = [int(id) for id in post_ranking]
    # get most viewed posts
    most_viewed = list(Post.objects.filter(
        id__in=post_ranking_ids))
    most_viewed.sort(key=lambda x: post_ranking_ids.index(x.id))
    return render(request,
                  'article/ranking.html',
                  {'most_viewed': most_viewed})

templates/article/create.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load thumbnail %}
{% block title %}{% trans "Create a post" %}{% endblock %}
{% block content %}
    {% thumbnail user.profile.avatar "300x300" crop="100%" as im %}
        <a href="{{ user.get_absolute_url }}"><img src="{{ im.url }}" style="width:65px;"
                                                   class="w3-circle w3-right w3-margin w3-hide-large w3-hover-opacity"></a>
        </a>
    {% endthumbnail %}
    <span class="w3-button w3-hide-large w3-xxlarge w3-hover-text-grey" onclick="w3_open()"><i
            class="fa fa-bars"></i></span>
    <div class="w3-container w3-padding-large" style="margin-bottom:32px">
        <h1>{% trans "Create a post" %}</h1>
        <form action="." method="post" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            <p><label for="id_title">{% trans "Title:" %}</label> {{ form.title }}</p>
            <p><label for="id_avatar">{% trans "Avatar:" %}</label> {{ form.avatar }}</p>
            <p><label for="id_price">{% trans "Price:" %}</label> {{ form.price }}</p>
            <p><label
                    for="id_tags">{% trans "Tags (Separated with comma, can be 'Goods' or 'Needs'):" %}</label> {{ form.tags }}
            </p>
            <div id="editormd">
                <textarea name="body" id="id_body" style="display:none"></textarea>
            </div>
            <input type="submit" value="{% trans 'Create' %}" class="w3-button w3-white">
        </form>
    </div>
{% endblock %}
{% block domready %}
    <script>
        $(function () {
            var editor = editormd("editormd", {
                height: 600,
                syncScrolling: "single",
                path: "{% static 'editormd/lib/' %}" // Autoload modules mode, codemirror, marked... dependents libs path
            });
        });
    </script>
{% endblock %}

templates/article/detail.html
{% extends 'base.html' %}
{% load article_tags %}
{% load thumbnail %}
{% load static %}
{% load i18n %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <header>
        {% thumbnail user.profile.avatar "300x300" crop="100%" as im %}
            <a href="{{ user.get_absolute_url }}"><img src="{{ im.url }}" style="width:65px;"
                                                       class="w3-circle w3-right w3-margin w3-hide-large w3-hover-opacity"></a>
            </a>
        {% endthumbnail %}
        <span class="w3-button w3-hide-large w3-xxlarge w3-hover-text-grey" onclick="w3_open()"><i
                class="fa fa-bars"></i></span>
        <div class="w3-container">
            <h1><b>{{ post.title }}</b></h1>
            <div class="w3-section w3-bottombar w3-padding-16">
                <span class="count">
                    <button class="w3-button w3-{% if request.user not in post.users_like.all %}white{% else %}black{% endif %}"
                            id="like-button">
                        <i class="fas fa-heart"></i>
                        <span class="total">{{ post.users_like.count }}</span>
                    </button>
                </span>

                <span class="count">
                    <button class="w3-button w3-white w3-hide-small">
                        <i class="fas fa-eye"></i>
                        {{ total_views }}
                    </button>
                </span>

                <button class="w3-button w3-white w3-hide-small">
                    <i class="fas fa-money-bill-alt"></i>
                    {{ post.price }}
                </button>


                {% if request.user == post.author %}
                    <a href="{% url "article:post_update" post.id %}" class="w3-button w3-white w3-hide-small"><i
                            class="fas fa-edit"></i>{% trans "Update" %}</a>
                    <a href="{% url "article:post_delete" post.id %}" class="w3-button w3-white w3-hide-small"><i
                            class="fas fa-trash"></i>{% trans "Delete" %}</a>
                {% endif %}

                <!-- Like button DON'T TRANSLATE-->
                <a href="#" data-id="{{ post.id }}"
                   data-action="{% if request.user in post.users_like.all %}un{% endif %}like"
                   class="like button" id="like-link" style="display: none;">
                    {% if request.user not in post.users_like.all %}
                        Like
                    {% else %}
                        Unlike
                    {% endif %}
                </a>

            </div>
        </div>
    </header>
    <div class="w3-row">
        <!-- Big cards -->
        <div class="w3-col l8 s12">
            <!-- Detail card -->
            <div class="w3-card-4 w3-margin w3-white">
                <img src="{{ post.avatar.url }}" style="width:100%">
                <div class="w3-container">
                    <h3><b>{{ post.title }}</b></h3>
                    <h5><a href="#">{{ post.author }}</a>, <span class="w3-opacity">{{ post.created }}</span>
                    </h5>
                </div>

                <div class="w3-container">
                    <p>{{ post.body|markdown }}</p>
                    <div class="w3-row">
                        <div class="w3-col m8 s12">
                            <p>
                                <a class="w3-button w3-padding-large w3-white w3-border"
                                   href="{% url 'actions:conversation' post.author.id %}"><b>{% trans "CONTACT" %}
                                    &raquo;</b>
                                </a>
                            </p>
                        </div>
                        <div class="w3-col m4 w3-hide-small">
                            <p><span class="w3-padding-large w3-right"><b>{% trans "Comments" %} &nbsp;</b> <span
                                    class="w3-tag">{{ comments.count }}</span></span></p>
                        </div>
                    </div>
                </div>
            </div>
            <hr>

            <!-- Add comment card -->
            <div class="w3-card-4 w3-margin">
                <div class="w3-container w3-padding">
                    <h4>{% trans "Add a new comment" %}</h4>
                </div>
                <div class="w3-container w3-white">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div id="editormd">
                            <textarea name="body" id="id_body" style="display:none" required></textarea>
                        </div>
                        <p><input type="submit" value="{% trans 'Add comment' %}"
                                  class="w3-button w3-padding-large w3-white w3-border"></p>
                    </form>
                </div>
            </div>

            <!-- Comment card -->
            <div class="w3-card-4 w3-margin">
                <div class="w3-container w3-padding">
                    <h4>{% trans "Comments" %}</h4>
                </div>
                <ul class="w3-ul w3-hoverable w3-white">
                    {% for comment in comments %}
                        <li class="w3-padding-16">
                            {% with user=comment.author %}
                                {% thumbnail user.profile.avatar "80x80" crop="100%" as im %}
                                    <a href="{{ user.get_absolute_url }}">
                                        <img src="{{ im.url }}" alt="Image" class="w3-left w3-margin-right"
                                             style="width:50px">
                                    </a>
                                {% endthumbnail %}
                                <span class="w3-large">
                                    #{{ forloop.counter }} <a
                                        href="{{ comment.author.get_absolute_url }}">{{ comment.author.username }}</a>,
                                    <span class="w3-opacity">{{ comment.created }}</span>
                                </span><br>
                                <span>{{ comment.body|markdown }}</span>
                            {% endwith %}
                        </li>
                    {% empty %}
                        <div class="w3-container w3-white">
                            <p>{% trans "There are no comments yet." %}</p>
                        </div>
                    {% endfor %}
                </ul>
            </div>
            <!-- END BIG CARDS -->
        </div>

        <!-- Introduction menu -->
        <div class="w3-col l4">
            <!-- About Card -->
            <div class="w3-card w3-margin w3-margin-top">
                {% thumbnail post.author.profile.avatar "300x300" crop="100%" as im %}
                    <a href="{{ user.get_absolute_url }}">
                        <img src="{{ im.url }}" style="width:100%">
                    </a>
                {% endthumbnail %}
                <div class="w3-container w3-white">
                    <h4><b>{{ post.author.username }}</b></h4>
                    <p>{{ post.author.profile.description|markdown|truncatewords_html:30 }}</p>
                </div>
            </div>
            <hr>
            <!-- Liked by card -->
            <div class="w3-card w3-margin">
                <div class="w3-container w3-padding">
                    <h4>{% trans "Liked by" %}</h4>
                </div>
                {% include 'information/list_ul.html' with users=post.users_like.all %}
            </div>
            <hr>

            <!-- Labels / tags -->
            <div class="w3-card w3-margin">
                <div class="w3-container w3-padding">
                    <h4>{% trans "Tags" %}</h4>
                </div>
                <div class="w3-container w3-white">
                    <p>
                        {% for tag in post.tags.all %}
                            <a class="w3-tag w3-light-grey w3-margin-bottom" style="text-decoration: none"
                               href="{% url 'article:post_list' %}?tag={{ tag }}">
                                {{ tag }}
                            </a>
                        {% empty %}
                            {% trans "There are no tags yet." %}
                        {% endfor %}
                    </p>
                </div>
            </div>
            <hr>

            <!-- Similar posts card -->
            <div class="w3-card w3-margin">
                <div class="w3-container w3-padding">
                    <h4>{% trans "Similar posts" %}</h4>
                </div>
                <ul class="w3-ul w3-hoverable w3-white">
                    {% for post in similar_posts %}
                        <li class="w3-padding-16">
                            {% thumbnail post.avatar "80x80" crop="100%" as im %}
                                <a href="{{ post.get_absolute_url }}">
                                    <img src="{{ im.url }}" alt="Image" class="w3-left w3-margin-right"
                                         style="width:50px">
                                </a>
                            {% endthumbnail %}
                            <span class="w3-large">{{ post.title|truncatewords:5 }}</span><br>
                            <span style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; display: block">{{ post.body }}</span>
                        </li>
                    {% empty %}
                        <div class="w3-container w3-white">
                            <p>{% trans "There are no similar posts yet." %}</p>
                        </div>
                    {% endfor %}
                </ul>
            </div>
            <!-- END Introduction Menu -->
        </div>
    </div>
{% endblock %}
{% block domready %}
    <script>
        $(document).ready(function () {
            $('a.like').click(function (e) {
                e.preventDefault();
                $.post('{% url "article:post_like" %}',
                    {
                        id: $(this).data('id'),
                        action: $(this).data('action')
                    },
                    function (data) {
                        if (data['status'] == 'ok') {
                            var previous_action = $('a.like').data('action');

                            // toggle data-action
                            $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
                            // toggle link text
                            $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');

                            // update total likes
                            var previous_likes = parseInt($('span.count .total').text());
                            $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);

                            if (previous_action == 'like')
                                $('#like-button').removeClass('w3-white').addClass('w3-black');
                            else $('#like-button').removeClass('w3-black').addClass('w3-white');
                        }
                    }
                );
            });
            $('#like-button').click(function (e) {
                $('#like-link').click();
                return false;
            });
            $(function () {
                var editor = editormd("editormd", {
                    height: 320,
                    syncScrolling: "single",
                    path: "{% static 'editormd/lib/' %}" // Autoload modules mode, codemirror, marked... dependents libs path
                });
            });
        });
    </script>
{% endblock %}

templates/article/list_ajax.html
{% load article_tags %}
{% load thumbnail %}
{% load i18n %}
<div class="w3-row-padding">
    {% for post in posts %}
        <div class="w3-third w3-container w3-margin-bottom">
            {% thumbnail post.avatar "300x300" crop="100%" as im %}
                <a href="{{ post.get_absolute_url }}">
                    <img src="{{ im.url }}" style="width:100%" class="w3-hover-opacity">
                </a>
            {% endthumbnail %}
            <div class="w3-container w3-white">
                <p style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; display: block">
                    <b>{{ post.title }}</b></p>
                <p class="w3-opacity"
                   style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; display: block">{{ post.price }}¥</p>
                <div style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; display: block">
                    {% for tag in post.tags.all %}
                        <a class="w3-tag w3-light-grey w3-margin-bottom" style="text-decoration: none"
                           href="{% url 'article:post_list' %}?tag={{ tag }}">
                            {{ tag }}
                        </a>
                    {% empty %}
                        <a class="w3-tag w3-light-grey w3-margin-bottom" style="text-decoration: none"
                           href="{% url 'article:post_list' %}?tag=需求">
                            {% trans "Needs" %}
                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% empty %}
        <div class="w3-container w3-white">
            <p>{% trans "There are no posts yet." %}</p>
        </div>
    {% endfor %}
</div>

templates/article/share.html
{% extends "article/../base.html" %}
{% load i18n %}
{% block title %}{% trans "Share a post" %}{% endblock %}

{% block content %}
    {% if sent %}
        <h1>{% trans "E-mail successfully sent" %}</h1>
        <p>
            "{{ post.title }}" {% trans "was successfully sent to" %} {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>{% trans "Share" %} "{{ post.title }}"</h1>
        <form action="" method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="{% trans 'Send e-mail' %}">
        </form>
    {% endif %}
{% endblock %}

templates/article/update.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load thumbnail %}
{% block title %}
    {% trans "Update a post" %}
{% endblock %}
{% block content %}
    {% thumbnail user.profile.avatar "300x300" crop="100%" as im %}
        <a href="{{ user.get_absolute_url }}"><img src="{{ im.url }}" style="width:65px;"
                                                   class="w3-circle w3-right w3-margin w3-hide-large w3-hover-opacity"></a>
        </a>
    {% endthumbnail %}
    <span class="w3-button w3-hide-large w3-xxlarge w3-hover-text-grey" onclick="w3_open()"><i
            class="fa fa-bars"></i></span>
    <div class="w3-container w3-padding-large" style="margin-bottom:32px">
        <h1>{% trans "Update a post" %}</h1>
        <form action="." method="post" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            <p><label for="id_title">{% trans "Title:" %}</label> {{ form.title }}</p>
            <p><label for="id_avatar">{% trans "Avatar:" %}</label> {{ form.avatar }}</p>
            <p><label for="id_price">{% trans "Price:" %}</label> {{ form.price }}</p>
            <div id="editormd">
                <textarea name="body" id="id_body" style="display:none">{{ form.body.value }}</textarea>
            </div>
            <input type="submit" value="{% trans 'Update' %}" class="w3-button w3-white">
        </form>
    </div>
{% endblock %}
{% block domready %}
    <script>
        $(function () {
            var editor = editormd("editormd", {
                height: 640,
                syncScrolling: "single",
                path: "{% static 'editormd/lib/' %}" // Autoload modules mode, codemirror, marked... dependents libs path
            });
        });
    </script>
{% endblock %}